// Code generated by mockery v2.33.1. DO NOT EDIT.

package mocks

import (
	models "prueba_meli/internal/domain/models"

	mock "github.com/stretchr/testify/mock"
)

// SateliteService is an autogenerated mock type for the SateliteService type
type SateliteService struct {
	mock.Mock
}

// GetAllSatelites provides a mock function with given fields:
func (_m *SateliteService) GetAllSatelites() ([]models.Satellite, error) {
	ret := _m.Called()

	var r0 []models.Satellite
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Satellite, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Satellite); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Satellite)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLocation provides a mock function with given fields: distances
func (_m *SateliteService) GetLocation(distances ...float32) (float32, float32) {
	_va := make([]interface{}, len(distances))
	for _i := range distances {
		_va[_i] = distances[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 float32
	var r1 float32
	if rf, ok := ret.Get(0).(func(...float32) (float32, float32)); ok {
		return rf(distances...)
	}
	if rf, ok := ret.Get(0).(func(...float32) float32); ok {
		r0 = rf(distances...)
	} else {
		r0 = ret.Get(0).(float32)
	}

	if rf, ok := ret.Get(1).(func(...float32) float32); ok {
		r1 = rf(distances...)
	} else {
		r1 = ret.Get(1).(float32)
	}

	return r0, r1
}

// GetMesage provides a mock function with given fields: messages
func (_m *SateliteService) GetMessage(messages ...[]string) string {
	_va := make([]interface{}, len(messages))
	for _i := range messages {
		_va[_i] = messages[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 string
	if rf, ok := ret.Get(0).(func(...[]string) string); ok {
		r0 = rf(messages...)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetSateliteByName provides a mock function with given fields: sateliteName
func (_m *SateliteService) GetSateliteByName(sateliteName string) (models.Satellite, error) {
	ret := _m.Called(sateliteName)

	var r0 models.Satellite
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Satellite, error)); ok {
		return rf(sateliteName)
	}
	if rf, ok := ret.Get(0).(func(string) models.Satellite); ok {
		r0 = rf(sateliteName)
	} else {
		r0 = ret.Get(0).(models.Satellite)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(sateliteName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveSatelite provides a mock function with given fields: satelites
func (_m *SateliteService) SaveSatelite(satelites models.Satellite) error {
	ret := _m.Called(satelites)

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Satellite) error); ok {
		r0 = rf(satelites)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ShowMessagesAndLocation provides a mock function with given fields: satelites
func (_m *SateliteService) ShowMessagesAndLocation(satelites []models.Satellite) (models.MessageAndLocation, error) {
	ret := _m.Called(satelites)

	var r0 models.MessageAndLocation
	var r1 error
	if rf, ok := ret.Get(0).(func([]models.Satellite) (models.MessageAndLocation, error)); ok {
		return rf(satelites)
	}
	if rf, ok := ret.Get(0).(func([]models.Satellite) models.MessageAndLocation); ok {
		r0 = rf(satelites)
	} else {
		r0 = ret.Get(0).(models.MessageAndLocation)
	}

	if rf, ok := ret.Get(1).(func([]models.Satellite) error); ok {
		r1 = rf(satelites)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSateliteService creates a new instance of SateliteService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSateliteService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SateliteService {
	mock := &SateliteService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
